# -*- coding: utf-8 -*-

import copy

website = """<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/pygment_trac.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/extra.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/print.css" media="print" />
	$style

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <title>$title</title>
  </head>

  <body>
    <header>
      <div class="inner">
        <h1><a href="http://jak-o-shadows.github.io/index.html">Jak_o_Shadows Web</a></h1>
        <h2>THINK. SOLVE. DESIGN. CREATE. TRANSFORM. ENGINEER.</h2>
        <!--<a href="https://github.com/jasonlong/architect-theme" class="button"><small>View project on</small> GitHub</a>-->
		  <div id="menu">
			<ul>
				<li class="first"><a href="http://jak-o-shadows.github.io/blender/blender.html">Blender</a></li>
				<li><a href="http://jak-o-shadows.github.io/electronics/electronics.html">Electronics</a></li>
				<li><a href="http://jak-o-shadows.github.io/python/python.html">Python</a></li>
				<li><a href="http://jak-o-shadows.github.io/wr/wr.html">Water Rockets</a></li>
				<li><a href="http://jak-o-shadows.github.io/calculator/casio.html">Calculator Programs</a></li>
				<li><a href="http://jak-o-shadows.github.io/nerf/nerf.html">Nerf</a></li>
                <li><a href="http://jak-o-shadows.github.io/linux/linux.html">Linux</a></li>
			</ul>
		</div>
		
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">

        $contents
		<!---
        <div class="highlight">
		<pre><span class="nb">require</span> <span class="s1">'redcarpet'</span>
<span class="n">markdown</span> <span class="o">=</span> <span class="no">Redcarpet</span><span class="o">.</span><span class="n">new</span><span class="p">(</span><span class="s2">"Hello World!"</span><span class="p">)</span>
<span class="nb">puts</span> <span class="n">markdown</span><span class="o">.</span><span class="n">to_html</span></pre>
        </div>---->

		</section>
        <aside id="sidebar">
		<p>$first</p>
		<p>$second</p>
		<!--
          <a href="https://github.com/jasonlong/architect-theme/archive/master.zip" class="button">
            <small>Download</small>
            .zip file
          </a>
          <a href="https://github.com/jasonlong/architect-theme/archive/master.tar.gz" class="button">
            <small>Download</small>
            .tar.gz file
          </a>-->

          <p class="repo-owner"><a href="https://github.com/jasonlong/architect-theme">architect-theme</a> is maintained by <a href="https://github.com/jasonlong">jasonlong</a>. Modified by Jak_o_Shadows</p>

          <!--<p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.</p>-->
		  <p>This page was last modified: $time</p>
        </aside>
      </div>
    </div>

  </body>
</html>

"""

def nonCheetah(title, style, contents, time, first, second):
    t = copy.deepcopy(website)
    
    # Replace bits
    t = t.replace("<title>$title</title>", "<title>%s</title>" % title)
    
    t = t.replace("	$style", "	%s" % style)
    
    t = t.replace("        $contents", contents)
    
    t = t.replace(" $time</p>", " %s</p>" % time)
    

    return t


