# -*- coding: utf-8 -*-
website = """<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/pygment_trac.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/extra.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="http://jak-o-shadows.github.io/stylesheets/print.css" media="print" />
	$style

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <title>$title</title>
  </head>

  <body>
    <header>
      <div class="inner">
        <h1><a href="http://jak-o-shadows.github.io/index.html">Jak_o_Shadows Web</a></h1>
        <h2>I really need a tagline</h2>
        <!--<a href="https://github.com/jasonlong/architect-theme" class="button"><small>View project on</small> GitHub</a>-->
		  <div id="menu">
			<ul>
				<li class="first"><a href="http://jak-o-shadows.github.io/blender/blender.html">Blender</a></li>
				<li><a href="http://jak-o-shadows.github.io/electronics/electronics.html">Electronics</a></li>
				<li><a href="http://jak-o-shadows.github.io/python/python.html">Python</a></li>
				<li><a href="http://jak-o-shadows.github.io/wr/wr.html">Water Rockets</a></li>
				<li><a href="http://jak-o-shadows.github.io/calculator/casio.html">Calculator Programs</a></li>
				<li><a href="http://jak-o-shadows.github.io/nerf/nerf.html">Nerf</a></li>
                <li><a href="http://jak-o-shadows.github.io/linux/linux.html">Linux</a></li>
			</ul>
		</div>
		
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">

        $contents
		<!---
        <div class="highlight">
		<pre><span class="nb">require</span> <span class="s1">'redcarpet'</span>
<span class="n">markdown</span> <span class="o">=</span> <span class="no">Redcarpet</span><span class="o">.</span><span class="n">new</span><span class="p">(</span><span class="s2">"Hello World!"</span><span class="p">)</span>
<span class="nb">puts</span> <span class="n">markdown</span><span class="o">.</span><span class="n">to_html</span></pre>
        </div>---->

		</section>
        <aside id="sidebar">
		<p>$first</p>
		<p>$second</p>
		<!--
          <a href="https://github.com/jasonlong/architect-theme/archive/master.zip" class="button">
            <small>Download</small>
            .zip file
          </a>
          <a href="https://github.com/jasonlong/architect-theme/archive/master.tar.gz" class="button">
            <small>Download</small>
            .tar.gz file
          </a>-->

          <p class="repo-owner"><a href="https://github.com/jasonlong/architect-theme">architect-theme</a> is maintained by <a href="https://github.com/jasonlong">jasonlong</a>. Modified by Jak_o_Shadows</p>

          <!--<p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.</p>-->
		  <p>This page was last modified: $time</p>
        </aside>
      </div>
    </div>

  </body>
</html>

"""

def nonCheetah(title, style, contents, time, first, second):
    t = """
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>

  
  <meta content="text/html; charset=ISO-8859-1" http-equiv="content-type"><title>{!0}</title></head><body>{!1}

<table style="text-align: left; width: 100%;" border="0" cellpadding="2" cellspacing="2">

  <tbody>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td colspan="2" rowspan="1" style="vertical-align: top; text-align: center;"><a href="http://jak-o-shadows.users.sourceforge.net">Jak-o-Shadows Web</a><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><a href="http://jak-o-shadows.users.sourceforge.net/blender/blender.html">Blender</a><br>
      </td>
      <td style="vertical-align: top;"><a href="http://jak-o-shadows.users.sourceforge.net/electronics/electronics.html">Electronics<br>
      </a>
      </td>
      <td style="vertical-align: top;"><a href="http://jak-o-shadows.users.sourceforge.net/python/python.html">Python</a><br>
      </td>
      <td style="vertical-align: top;"><a href="http://jak-o-shadows.users.sourceforge.net/wr/wr.html">Water Rockets</a><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td colspan="3" rowspan="1" style="vertical-align: top;"><br>{!2}
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;"><br>
      </td>
      <div id="first">{4}</div>
<br />
<div id="second">{5}</div>
      <td colspan="4" rowspan="1" style="vertical-align: top;">Last update was on {!3}<br />All
works licensed under the GPL general public license v3, unless
otherwise noted. Content may include works based upon public domain
content.<br>
      </td>
      <td style="vertical-align: top;"><br>
      </td>
    </tr>
  </tbody>
</table>

<br>

<br>


</body></html>
""".format(title, style, contents, time, first, second)                
    return t


